### ISSUE TITLE
InterpViewer: Interpreter tab does not update

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#185] opened 2020-06-14 17:07 UTC
In the Interpviewer tool, edits made in the Interpreter tab are not shown as changed in the tab itself. Saving reviews that the tab did indeed update the underlying file, just didn't refresh the tab.

To reproduce:
Open any conversation or interpdata.  Open in Interpviewer.  Click on a line, make changes in the interpreter tab.

Click away and back to force the tab to refresh and see the changes have been implemented.

**Comment by Mgamerz** [comment] 2020-06-14 17:11
This issue is due to changes when I added interpreter to it on the big endian branch. The issue is partially due to the fact that curve editor updates the export constantly while the point is moving, which would cause the box to constantly refresh. I don't think I ever hooked it back up to refresh properly though. It likely needs to be checked in handleUpdate() for that tool window.

**Closed as completed** 2020-07-21 20:32 UTC
