### ISSUE TITLE
Incorrect Camera Data in Meshplorer view

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#260] opened 2021-07-06 16:35 UTC
**Bug description**
The X, Y and Z camera data listed in Meshplorer's "Camera Data" tab appears to be displayed incorrectly.

**Why it's an issue**
You can use mesh data to create anchored camera shots for cutscenes and events, if the data is correctly displayed.

**To Reproduce**
Open a file, I did through Package Editor and find a mesh, toggle the Camera Data view, and see if it matches up reasonably well.

Additional example
1. If you check the Mesh of a BioStage, found in any BioD file that has a "LOC_" file associated. Easiest: The "Common 2P stage" in the BioD_Nor510_CargoConv.pcc file.
2. Compare the data provded if you imagine both triangles are "characters" and what camera location values are listed in the Mesh's binary:
2.1. Under "RefSkeleton" find "Cam2_1_3" or "Cam1_2_3", the most commonly used "shots" in the James Investigate conversation.
2.2. Try finding the same values in Camera Data (just the location, because Pitch/Yaw appear correct)
2.3. Compare how the shot of the stage mesh looks compared to the framing in game.

**Expected behavior**
The Y and X values should not be equal. The Z value (up and down) should not change when I'm rotating horizontally around the mesh.

**Screenshots and files used to replicate this**
![billede](https://user-images.githubusercontent.com/17158981/124636283-a9c34f80-de88-11eb-943b-6a67508db1dc.png)

(Screenshot: Not a particular example, just demonstrating that X and Y appear to be equal and Z shows a crazy value that changes by rotating on the wrong axis.)

**Version information:**
Tested on old ME3Explorer 5.1 5-16-2021 build and the first public beta edition of LEX 6-29-2021.

**Comment by henbagle** [comment] 2021-07-06 16:39
Just to confirm, this issue is present in both ME3Explorer 5.1 and in LEX? We changed some behind the scenes 3D stuff for LEX and I want to verify that this is an existing bug and not a bug introduced with the move to System.Numerics

**Comment by linkenski** [comment] 2021-07-06 21:56
Same issue in new and old version, LEX and pre-LEX so I don’t think that’s the cause.

**Comment by henbagle** [comment] 2021-08-16 16:24
Coordinates have been fixed in the latest nightly so Z is up. I'm still not sure if the other two axes are in the correct orientation, but some quick testing with a BioStage seemed to show that they are correct, though I think I had to negate the X axis.

**Closed as completed** 2021-08-31 02:35 UTC
