### ISSUE TITLE
Can't connect Interp ins and outs in latest builds' SeqEd

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#138] opened 2019-06-18 18:58 UTC
**Describe the bug**
You get some OutOfRange exception when you try to connect two in or out points of Interp objects.

**To Reproduce**
Open any file, from my experience, say in a LOC_INT sequence, like an interp to a EndCurrentConvNode and try putting its Completed out to the In of the next object.

**Expected behavior**
An error-box pops up which gives an ArgumentOutOfRange Exception saying that the value mustn't be below null.

**Version information:**
Tried on release version 4.0.1 build 6-11-2019 and Nightly 4.1 6-17

**Comment by SirCxyrtyx** [comment] 2019-06-18 20:16
Can't reproduce. Can you give a specific Interp in a specific file that causes this when you try to connect to a specific EndCurrentConvNode?

**Comment by linkenski** [comment] 2019-06-19 15:47
[BioD_KroGar_220CampPawns_LOC_INT.zip](https://github.com/ME3Tweaks/ME3Explorer/files/3306861/BioD_KroGar_220CampPawns_LOC_INT.zip)
I just tried using this file and replicated the issue for myself. I've found that it doesn't bug out when I try to attach _any_ interp objects, however if you try going to the KroGar_general_m_d sequence and clone an interp and a ConvNode Start, then attatch that Start to the "Play" of the Interp, you get the error, or, at least, I do.

**Comment by linkenski** [comment] 2019-06-22 00:27
Realized a thing about this. It's the output links. Normally attaching it to an "in" it will know to create an array element with that data, but for whatever reason it can't do it if there's no array elements. If you have at least 1 it will create another array element and attach that. Probably as MGamerz or whomever suggested previously, that it can't do it if it's "-1" or something.

**Comment by SirCxyrtyx** [comment] 2019-07-24 04:59
fixed in dbee7f8829c2855a0429cabbd7cf4d503c931843

**Closed as completed by SirCxyrtyx** 2019-07-24 04:59 UTC
Labels: Needs more info
